// Sample webhook events from multiple Claude Code instances.
// Each event represents a status update sent via webhook — newest first.
// Status types: working, waiting, blocked, success, idle, approval, tests, reviewing
// `needs` is set when status === 'waiting' or 'approval' or 'blocked'

const NOW = new Date('2026-05-04T14:32:18');
const ago = (mins) => new Date(NOW.getTime() - mins * 60 * 1000);

const FEED_EVENTS = [
  {
    id: 'evt_8a3f',
    instance: 'cc-payments',
    repo: 'acme/checkout-api',
    branch: 'feat/stripe-3ds-flow',
    session: 'tmux:work.2',
    desktop: 'workspace 3',
    status: 'approval',
    title: 'Approve: rm -rf node_modules && pnpm install',
    detail: 'Wants to nuke node_modules to resolve a peer-dep conflict in @stripe/react-stripe-js. Last build failed with ERESOLVE.',
    needs: 'Approve a tool/command',
    elapsed: '00:14:32',
    ts: ago(0),
    tokens: '142k',
  },
  // ── subagents spawned by cc-payments ────────────────────────────
  {
    id: 'evt_8a3f_s1',
    parent: 'evt_8a3f',
    instance: 'cc-payments › audit-deps',
    role: 'subagent',
    status: 'success',
    title: 'Audited 47 dependencies for 3DS compatibility',
    detail: '4 packages flagged. @stripe/react-stripe-js has the peer-dep conflict; rest are clean.',
    elapsed: '00:02:18',
    ts: ago(1),
  },
  {
    id: 'evt_8a3f_s2',
    parent: 'evt_8a3f',
    instance: 'cc-payments › write-migration',
    role: 'subagent',
    status: 'working',
    title: 'Drafting migration script for legacy charges → PaymentIntents',
    detail: 'Streaming 2014–2019 charges through the converter. ETA ~6m.',
    elapsed: '00:05:42',
    ts: ago(0.5),
  },
  {
    id: 'evt_7d2c',
    instance: 'cc-mobile',
    repo: 'acme/ios-app',
    branch: 'fix/onboarding-crash',
    session: 'tmux:mobile.0',
    desktop: 'workspace 2',
    status: 'waiting',
    title: 'Pick a strategy for the AuthContext race condition',
    detail: 'Two viable fixes: (a) gate the splash on a hydration promise, (b) move auth state into a Zustand store with a selector. Which do you prefer?',
    needs: 'Pick between options',
    elapsed: '00:08:11',
    ts: ago(2),
    tokens: '88k',
  },
  {
    id: 'evt_9f1b',
    instance: 'cc-infra',
    repo: 'acme/terraform',
    branch: 'chore/upgrade-eks-1.30',
    session: 'tmux:ops.1',
    desktop: 'workspace 4',
    status: 'blocked',
    title: 'Plan failed — IAM role missing eks:DescribeCluster',
    detail: 'terraform plan errored out on aws_eks_cluster.primary. Need policy update on TerraformDeployRole or a fresh AWS_PROFILE.',
    needs: 'Resolve merge conflict',
    elapsed: '00:21:04',
    ts: ago(4),
    tokens: '67k',
  },
  {
    id: 'evt_6e4a',
    instance: 'cc-docs',
    repo: 'acme/handbook',
    branch: 'docs/runbooks-q2',
    session: 'tmux:writing.0',
    desktop: 'workspace 1',
    status: 'working',
    title: 'Drafting incident runbook for the auth-service',
    detail: 'Working through the on-call escalation matrix. Cross-referencing past incidents IR-2031, IR-2044.',
    elapsed: '00:32:48',
    ts: ago(6),
    tokens: '221k',
  },
  {
    id: 'evt_6e4a_s1',
    parent: 'evt_6e4a',
    instance: 'cc-docs › incident-search',
    role: 'subagent',
    status: 'reviewing',
    title: 'Scanning past incident reports for auth-service patterns',
    detail: 'Read IR-2031, IR-2044, IR-2058. Pulling escalation timing data.',
    elapsed: '00:01:42',
    ts: ago(7),
  },
  {
    id: 'evt_5b9d',
    instance: 'cc-platform',
    repo: 'acme/platform',
    branch: 'main',
    session: 'tmux:work.0',
    desktop: 'workspace 3',
    status: 'tests',
    title: 'Running pnpm test:integration',
    detail: '47 / 312 passed. Suite: billing/subscriptions. Estimated 4m remaining.',
    elapsed: '00:04:22',
    ts: ago(9),
    tokens: '54k',
  },
  {
    id: 'evt_5b9d_s1',
    parent: 'evt_5b9d',
    instance: 'cc-platform › flake-investigator',
    role: 'subagent',
    status: 'blocked',
    title: 'Webhook test flaking on retry-after header',
    detail: 'Race between fake timer and the BullMQ scheduler. Need to decide between mocking BullMQ or extending the deadline.',
    needs: 'Pick between options',
    elapsed: '00:03:11',
    ts: ago(8),
  },
  {
    id: 'evt_5b9d_s2',
    parent: 'evt_5b9d',
    instance: 'cc-platform › coverage-reporter',
    role: 'subagent',
    status: 'working',
    title: 'Streaming coverage diffs to the PR thread',
    detail: 'Posting per-file deltas as suites complete.',
    elapsed: '00:04:01',
    ts: ago(8.5),
  },
  {
    id: 'evt_4c8e',
    instance: 'cc-data',
    repo: 'acme/analytics',
    branch: 'feat/funnel-v3',
    session: 'tmux:data.1',
    desktop: 'workspace 5',
    status: 'reviewing',
    title: 'Reading through the existing funnel pipeline',
    detail: 'Building a mental model of the dbt graph before proposing the v3 schema. 14 models reviewed, 8 to go.',
    elapsed: '00:18:55',
    ts: ago(13),
    tokens: '178k',
  },
  {
    id: 'evt_3a7f',
    instance: 'cc-mobile-2',
    repo: 'acme/android-app',
    branch: 'feat/biometric-login',
    session: 'tmux:mobile.1',
    desktop: 'workspace 2',
    status: 'success',
    title: 'Pushed feat/biometric-login → CI passing',
    detail: 'All 248 tests green. Bundle size +1.4kb. Ready for review when you are.',
    elapsed: '00:42:11',
    ts: ago(22),
    tokens: '312k',
  },
  {
    id: 'evt_2d6c',
    instance: 'cc-web',
    repo: 'acme/marketing',
    branch: 'redesign/pricing-page',
    session: 'tmux:web.0',
    desktop: 'workspace 1',
    status: 'waiting',
    title: 'Need the new pricing tier copy',
    detail: 'I have layout for Starter / Team / Enterprise but the Team tier copy is still TBD per the brief.',
    needs: 'Provide a file or paste',
    elapsed: '00:11:09',
    ts: ago(31),
    tokens: '94k',
  },
  {
    id: 'evt_1f5b',
    instance: 'cc-infra-2',
    repo: 'acme/observability',
    branch: 'main',
    session: 'tmux:ops.2',
    desktop: 'workspace 4',
    status: 'idle',
    title: 'Standing by',
    detail: 'No active task. Waiting for the next instruction.',
    elapsed: '01:42:30',
    ts: ago(48),
    tokens: '12k',
  },
  {
    id: 'evt_0e4a',
    instance: 'cc-payments',
    repo: 'acme/checkout-api',
    branch: 'feat/stripe-3ds-flow',
    session: 'tmux:work.2',
    desktop: 'workspace 3',
    status: 'success',
    title: 'Refactored CheckoutSession.create to use 3DS challenge flow',
    detail: 'Tests passing locally. 4 files changed, +182 / -94. Ready for the next step.',
    elapsed: '00:28:14',
    ts: ago(64),
    tokens: '208k',
  },
  {
    id: 'evt_zz3a',
    instance: 'cc-docs',
    repo: 'acme/handbook',
    branch: 'docs/runbooks-q2',
    session: 'tmux:writing.0',
    desktop: 'workspace 1',
    status: 'reviewing',
    title: 'Surveying past runbook patterns',
    detail: 'Read 12 existing runbooks. Picking the strongest template to adapt.',
    elapsed: '00:09:02',
    ts: ago(88),
    tokens: '66k',
  },
  {
    id: 'evt_yy2b',
    instance: 'cc-platform',
    repo: 'acme/platform',
    branch: 'main',
    session: 'tmux:work.0',
    desktop: 'workspace 3',
    status: 'success',
    title: 'Merged: chore/bump-node-22',
    detail: 'CI green. Deployed to staging at 12:47.',
    elapsed: '00:51:20',
    ts: ago(112),
    tokens: '184k',
  },
];

// Status metadata — name, label, hue, glyph type
const STATUS_META = {
  approval:  { label: 'Awaiting approval', tone: 'attention', priority: 1 },
  waiting:   { label: 'Waiting on you',    tone: 'attention', priority: 1 },
  blocked:   { label: 'Blocked',           tone: 'danger',    priority: 2 },
  working:   { label: 'Working',           tone: 'active',    priority: 3 },
  tests:     { label: 'Running tests',     tone: 'active',    priority: 3 },
  reviewing: { label: 'Reviewing',         tone: 'active',    priority: 3 },
  success:   { label: 'Completed',         tone: 'success',   priority: 4 },
  idle:      { label: 'Idle',              tone: 'neutral',   priority: 5 },
};

window.FEED_EVENTS = FEED_EVENTS;
window.STATUS_META = STATUS_META;
window.NOW = NOW;
